DTS-STN/senior-journey

frontend/.prettierrc
frontend/app/entry.client.tsx
frontend/app/entry.server.tsx
frontend/package-lock.json
frontend/package.json

Install @trivago/prettier-plugin-sort-imports and format all files with Prettier
https://www.npmjs.com/package/@trivago/prettier-plugin-sort-imports

install @trivago/prettier-plugin-sort-imports

---

frontend/.prettierrc

Add ~/ imports to prettier importOrder

---

frontend/.dockerignore
frontend/Dockerfile

Cleaned up dockerfile; ensured correct file permissions in image; added OpenContainers meta labels.
``` shell
docker build . \                        
--build-arg BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
--build-arg BUILD_ID="0001" \
--build-arg BUILD_REVISION="$(git rev-parse --short=8 HEAD)" \
--build-arg BUILD_VERSION="$(date -u +%Y%m%d)-0001-$(git rev-parse --short=8 HEAD)" \
--tag sj-frontend
```
To inspect labels/metadata:
``` shell
docker inspect sj-frontend
```
To run in container:
``` shell
docker run --rm --publish 3000:3000 sj-frontend
```

Cleanup & enhance dockerfile

---

gitops/.gitignore
gitops/README.md
gitops/applications/seniors-journey-frontend/deployments.yaml
gitops/applications/seniors-journey-frontend/kustomization.yaml
gitops/applications/seniors-journey-frontend/services.yaml
gitops/environments/dev/configmaps.yaml
gitops/environments/dev/deployments.yaml
gitops/environments/dev/ingresses.yaml
gitops/environments/dev/kustomization.yaml
gitops/environments/dev/services.yaml

Adding some placeholder gitops manifests as a starting point.
I guess try executing the commands in the *Running the project* section in the README.. 🤷‍♂️

Add test deployments to gitops/ directory

---

frontend/Dockerfile

Fix broken default date in Dockerfile

---

frontend/package-lock.json
frontend/package.json

Incremental change in preparation for adding OpenTelemetry.

Disable nextjs telemetry in package.json

---

frontend/__tests__/components/ApplicationNameBar.test.tsx
frontend/__tests__/components/Footer.test.tsx
frontend/public/locales/en/common.json
frontend/public/locales/fr/common.json
frontend/src/components/ApplicationNameBar.tsx
frontend/src/components/Footer.tsx
frontend/src/components/Header.tsx
frontend/src/components/Layout.tsx

- Style and structural changes to the header, footer, application namebar and layout components. 
- Changes to the common translation files

attempting to sign again

---

frontend/.env.example
frontend/__tests__/utils/metrics.test.ts
frontend/next.config.js
frontend/open-telemetry.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/pages/_app.tsx
frontend/src/utils/metrics.ts

Add OpenTelemetry and Dynatrace support to frontend.
Dynatrace API is configured via environment variables (see provided `.env.example`).

[frontend] Add OpenTelemetry metrics and tracing

---

frontend/src/components/ApplicationNameBar.tsx
frontend/src/components/Breadcrumb.tsx
frontend/src/components/Header.tsx
frontend/src/pages/home.tsx

- Minor interface PR. Moved breadcrumbs into ApplicationNameBar and aligned them with the Figma designs.

Moved Breadcrumbs

---

frontend/package-lock.json
frontend/package.json
frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/src/components/Tabcordian.tsx
frontend/src/pages/home.tsx

- removed "home" page title section as it is not in the mockups
- added tab/accordion component as it was requested.

Removed errant page title, added tab/accordion component

---

frontend/src/components/Tabcordian.tsx

- added different styles between md and lg, specifically around tabs.
- also changed the padding of the md tab block

fixing tabs in the md view

---

frontend/__tests__/components/ActionButton.test.tsx
frontend/package-lock.json
frontend/package.json
frontend/src/components/ActionButton.tsx
frontend/src/components/LinkButton.tsx
frontend/src/components/Tabcordian.tsx
frontend/src/pages/home.tsx
frontend/tailwind.config.js

- Implements [tailwindcss-elevation](https://github.com/jonaskay/tailwindcss-elevation)
MD2 Elevation documentation
https://m2.material.io/design/environment/elevation.html#default-elevations

implements tailwindcss-elevation

---

infrastructure/terragrunt/nonprod/oauth-proxy-aad-application/terragrunt.hcl

[infrastructure] Add test environment to AD client

---

gitops/environments/test/ingresses.yaml
gitops/environments/test/oauth-proxy.cfg
gitops/environments/test/services.patch.yaml

[AB-20](https://dev.azure.com/JourneyLab/SeniorsJourney/_workitems/edit/20) -- ensure application on nonprod is not publicly accessible

[gitops] Enable OAuth proxy

---

frontend/__tests__/middleware.test.ts
frontend/src/middleware.ts
frontend/src/styles/globals.css

This commit fixes [AB#223](https://dev.azure.com/JourneyLab/e5439067-4cca-4d9d-9c04-19430d3be3db/_workitems/edit/223) (false positive "hidden files found" in OWASP ZAP due to `/*` page forwarding to `/en/*`).

[frontend] AB#223 -- change middleware redirects

---

frontend/src/pages/learn/retirement-income-sources.tsx
frontend/src/styles/globals.css

- adjusts font styles with Lato version 2.0 changes to match mockups
Load the application and go to `/en/learn/retirement-income-sources`
Page mockups
https://www.figma.com/file/fBuLkbEjrAiZSF1gO6SSQq/SJL---MATERIAL-2-Design-Files?node-id=70-10154&t=H8h6czEkwNFuwaS1-0

adjusts font styles with Lato version 2.0 changes

---

frontend/public/locales/en/learn.json
frontend/public/locales/fr/learn.json
frontend/src/pages/learn/index.tsx
frontend/src/styles/globals.css
frontend/tailwind.config.js

- Added Learn Page Content
- Imported Material-Tailwind
- Maps content from locale files

AB#227 Added Learn Page Content

---

frontend/src/pages/learn/planning-to-save-for-retirement.tsx
frontend/src/styles/globals.css

- remove some redundant HTML
- change links that open a new tab
- change window Y offset method because the other one was deprecated

AB#171 Planning To Save For Retirement Page

---

frontend/src/components/LearnPageLayout.tsx
frontend/src/pages/learn/planning-to-save-for-retirement.tsx
frontend/src/pages/learn/retirement-income-sources.tsx

- add reusable learn page layout

add reusable learn page layout

---

frontend/public/locales/en/home.json
frontend/public/locales/en/learn.json
frontend/public/locales/fr/home.json
frontend/public/locales/fr/learn.json
frontend/src/components/Tabcordian.tsx
frontend/src/pages/learn/index.tsx
frontend/src/pages/learn/retirement-income-sources.tsx

- Add missing learn pages navigation links.
- Tweak retirement income source content responsive layout.

Learn pages links and content

---

frontend/public/locales/en/common.json
frontend/public/locales/fr/common.json
frontend/src/components/LearnPageLayout.tsx
frontend/src/components/TableOfContents.tsx
frontend/src/lib/hooks/useTableOfContentsData.tsx

- Refactor table of contents by decoupling the logic that generate the TOC's data.

refactor table of contents

---

frontend/src/pages/learn/retirement-income-sources.tsx

fix learn more link style

---

frontend/package-lock.json
frontend/package.json
frontend/public/locales/en/learn.json
frontend/src/pages/learn/index.tsx
frontend/tailwind.config.js

- Learn Page cards now use MUI rather than material-tailwind
- Content updated to match latest designs

AB#278 Refactored Learn Page with MUI

---

frontend/src/components/Header.tsx

- fix hash in language toggle
Omit the location hash in the header's language toggle link.

fix hash in language toggle

---

frontend/src/pages/home.tsx
frontend/src/pages/learn/index.tsx
frontend/src/styles/globals.css

- Quick fix on the Home Page Banner Layout

AB#264 Home Banner Fix

---

frontend/src/components/Collapse.tsx
frontend/src/components/LearnPageLayout.tsx
frontend/src/components/TableOfContents.tsx
frontend/src/components/TableOfContentsCollapse.tsx
frontend/src/lib/hooks/useTableOfContentsData.tsx
frontend/src/lib/types.ts

- add TableOfContentsCollapse component for mobile view

add TableOfContentsCollapse component

---

frontend/src/pages/learn/index.tsx

- fix learn page layout
Don't use MUI component like Typography unless it's configure to work well with Tailwind.

fix learn page layout

---

frontend/src/components/TableOfContents.tsx
frontend/src/components/TableOfContentsCollapse.tsx

use List in TOC components

---

frontend/src/components/LearnPageLayout.tsx
frontend/src/pages/learn/planning-to-save-for-retirement.tsx
frontend/src/pages/learn/retirement-income-sources.tsx

- add Learn More section in LearnPageLayout

add Learn More section in LearnPageLayout

---

frontend/src/components/LearnPageLayout.tsx

- fix learn more section key on React.Fragment
- fix learn more section h3 instead of h6

fix learn more section

---

frontend/src/components/LearnPageLayout.tsx
frontend/src/pages/home.tsx
frontend/src/pages/index.tsx
frontend/src/pages/learn/index.tsx

- use next/link with component prop

use next/link with component prop

---

frontend/__mocks__/react-markdown.js
frontend/__tests__/components/TaskCard.test.tsx
frontend/cypress/e2e/404.cy.ts
frontend/package-lock.json
frontend/package.json
frontend/public/locales/en/quiz/tasks/task-list.json
frontend/public/locales/fr/quiz/task-list.json
frontend/src/components/MarkDown.tsx
frontend/src/components/MarkDownElements.tsx
frontend/src/components/NestedAccordion.tsx
frontend/src/components/ResourceTagButton.tsx
frontend/src/components/TaskCard.tsx
frontend/src/pages/quiz/tasks/task-list-print.tsx
frontend/src/pages/quiz/tasks/task-list.tsx

** signed  commit ** Contains pages for task list and associated components. The task text is markdown and the app uses MD JSX to convert to HTML elements 
- added task-list page for desktop viewing
- added task-list-print page for printing
- added Nested Accordion component to house the tasks
- added Markdown related components to transform it to HTML element
- added react-markdown library
npm i 
npm run dev
https://localhost:3000/[fr|en]/quiz/tasks/task-list
https://localhost:3000/[fr|en]/quiz/tasks/task-list-print
This is a bootstrap pages and component to build out when the design is completed.

based pages and components for task list

---

frontend/tailwind.config.js

- use Material UI breakpoints with Tailwind
-
Material UI
https://mui.com/material-ui/customization/breakpoints/#default-breakpoints
Tailwind
https://tailwindcss.com/docs/screens

use Material UI breakpoints with Tailwind

---

frontend/package-lock.json
frontend/package.json

- remove @material-tailwind/react package
-

remove @material-tailwind/react package

---

frontend/package-lock.json
frontend/package.json
frontend/public/locales/en/common.json
frontend/public/locales/fr/common.json
frontend/src/components/LearnPageLayout.tsx
frontend/src/components/TableOfContentsDialog.tsx

- add TOC Dialog component for learn pages

add TOC Dialog component

---

frontend/package-lock.json
frontend/package.json
frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/src/components/ApplicationNameBar.tsx
frontend/src/pages/home.tsx
frontend/tailwind.config.js

- Implemented tab content for home (home.json)
- Changed colouring for various elements (card backgrounds, footer's blue, header buttons)
- Implemented MUI based tab system

Restructuring, and colouring, the homepage to match mui designs

---

frontend/package-lock.json
frontend/package.json

- remove faker-js package since it's not used
-

[frontend] remove faker-js package

---

frontend/cypress/e2e/app.cy.ts
frontend/cypress/e2e/home.cy.ts
frontend/public/locales/en/common.json
frontend/public/locales/en/home.json
frontend/public/locales/fr/common.json
frontend/public/locales/fr/home.json
frontend/src/components/LearnPageLayout.tsx
frontend/src/next-seo.config.ts
frontend/src/pages/home.tsx
frontend/src/pages/index.tsx

- Set `Retirement Hub` application name to match mockups
- Remove the usage of `ListItemIcon` component

App name and list icons

---

frontend/__tests__/components/ApplicationNameBar.test.tsx
frontend/src/components/ApplicationNameBar.tsx
frontend/src/components/Header.tsx

- refactor ApplicationNameBar with Material UI components

[frontend] refactor ApplicationNameBar

---

frontend/public/locales/en/learn.json
frontend/public/locales/en/learn/from-work-to-retirement.json
frontend/public/locales/fr/learn.json
frontend/public/locales/fr/learn/from-work-to-retirement.json
frontend/src/pages/learn/from-work-to-retirement.tsx

From work to retirement learning content page based on the current design. Finalization work is needed once the design and content are approved.
- created from-work-to-retirement page
- added link on the FR/EN learn page
npm i
npm run dev
http://localhost:3000/en/learn/from-work-to-retirement
http://localhost:3000/fr/learn/from-work-to-retirement

create from-work-to-retirement learning content

---

frontend/src/theme.ts

- disable contained button elevation to match mockups
https://mui.com/material-ui/react-button/#contained-button

[frontend] disable contained button elevation

---

frontend/public/locales/en/common.json
frontend/public/locales/fr/common.json
frontend/src/components/Footer.tsx
frontend/src/components/Layout.tsx

- fix footer style to match the mockups

[frontend] fix footer style

---

frontend/src/pages/index.tsx

- use Material UI component style on index page

[frontend] use Material UI component style

---

frontend/src/pages/_document.tsx
frontend/src/utils/content-security-policy.ts

- Removed deprecated `prefetch-src` CSP directive

AB#317 -- deprecated CSP header

---

frontend/src/pages/home.tsx

- fix header typography to match mockups

[frontend] fix header typography

---

frontend/src/components/LearnPageLayout.tsx

- fix unselectable text when fab hover

[frontend] fix unselectable text when fab hover

---

frontend/public/locales/en/learn.json
frontend/public/locales/fr/learn.json
frontend/src/components/QuizLandingPage.tsx
frontend/src/pages/learn/index.tsx

- Added close confirmation on quiz
- Added responsivity for different screen sizes
- Close Modal to view new Confirmation screen

AB#148 Added Quiz Confirmation + Responsive

---

frontend/src/pages/learn/index.tsx

- remove custom css with Material UI Button

[frontend] remove custom css with Material UI Button

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/learn/index.tsx

- use Dialog instead of Modal
From Material UI:
https://mui.com/material-ui/react-modal
> If you are creating a modal dialog, you probably want to use the [Dialog](https://mui.com/material-ui/react-dialog/) component rather than directly using Modal.

[frontend] use Dialog instead of Modal

---

frontend/public/locales/en/learn.json
frontend/public/locales/fr/learn.json
frontend/src/components/questions/Question1.tsx
frontend/src/components/questions/Question2.tsx
frontend/src/pages/learn/index.tsx

new PR to get around retroactively signing commits.  See this PR (https://github.com/DTS-STN/senior-journey/pull/99)

quiz questions

---

frontend/public/locales/fr/home.json

- corrected the destination to the french find office link

Correcting french link for find-office

---

frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/src/pages/home.tsx
frontend/src/pages/learn/index.tsx
frontend/src/styles/globals.css

- Fixes two bugs on the home page
- Tabbed headers now bold on mobile
- Service Canada Phone Number corrected

AB#316 Fix Heading Bolding Issue and Phone Number

---

frontend/src/pages/quiz/tasks/[[...filters]].tsx

- change task page layout similar to Learn pages layout

[frontend] change task page layout

---

frontend/src/pages/_document.tsx
frontend/src/utils/content-security-policy.ts

This PR tightens up some of the Content Security Policy headers to make OWASP ZAP happy.

AB#175 -- Automate OWASP ZAP scans

---

frontend/src/components/questions/Question1.tsx
frontend/src/components/questions/Question2.tsx
frontend/src/components/questions/Question3.tsx
frontend/src/components/questions/Question4.tsx
frontend/src/components/questions/Question5.tsx
frontend/src/components/questions/Question6.tsx
frontend/src/components/questions/Question7.tsx
frontend/src/components/questions/Question8.tsx
frontend/src/data/tasks.json
frontend/src/pages/learn/index.tsx
frontend/src/pages/quiz/tasks/[[...filters]].tsx

- Submit quiz answers to tasks page

Submit quiz answers to tasks page

---

frontend/src/components/AlertCard.tsx
frontend/src/pages/learn/from-work-to-retirement.tsx
frontend/src/pages/learn/retirement-income-sources.tsx
frontend/src/pages/learn/rule-of-thumb-public-pensions.tsx
frontend/src/pages/learn/when-to-take-your-pensions.tsx

Changed the disclaimer and important and smart tip cards to a new design. 
- Added the responsive AlertCard component that can handle disclaimer, smart tip, and important styles
- Apply the AlertCard to all learning pages
npm i
npm run dev
navigate to the learning pages

Important card styling

---

frontend/__tests__/components/TaskCard.test.tsx
frontend/public/locales/en/quiz/tasks.json
frontend/public/locales/fr/quiz/tasks.json
frontend/src/components/NestedAccordion.tsx
frontend/src/components/TaskCard.tsx
frontend/src/data/tasks.json
frontend/src/lib/mappers/tasks-group-dto-mapper.ts
frontend/src/lib/types.ts
frontend/src/pages/quiz/tasks/[[...filters]].tsx

- filter added
- navigate to http://localhost:3000/en/quiz/tasks
- click the filters and observe how tasks are rendered depending on what tag(s) are selected
- test responsiveness of filter at different viewport widths
- test keyboard accessibility (all interactive elements should be keyboard accessible)

Left Menu - Filter Results

---

frontend/public/locales/en/common.json
frontend/public/locales/fr/common.json
frontend/src/components/Footer.tsx
frontend/src/components/Layout.tsx

- change styles to make links visible at smaller viewport widths

Landing  page - Terms and conditions and Privacy links not visible

---

frontend/src/components/questions/Question6.tsx

- change option number to get translations working correctly

[bug] Quiz - Step 6 of 8 - Text repeated twice for button

---

frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/public/locales/fr/learn/from-work-to-retirement.json
frontend/src/components/Container.tsx
frontend/src/components/Layout.tsx
frontend/src/components/NestedAccordion.tsx
frontend/src/pages/home.tsx

- update home to match mockups

[frontend] update home to match mockups

---

frontend/__tests__/components/Footer.test.tsx
frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/src/pages/home.tsx

- fix Footer tests TS typecheck
- remove Support Seniors section on Home page based on mockups

Home page remove section

---

frontend/src/pages/home.tsx

- fix home tabs accessibility issue

[frontend] fix home tabs accessibility issue

---

frontend/__tests__/components/Breadcrumb.test.tsx
frontend/public/locales/en/home.json
frontend/public/locales/en/learn.json
frontend/public/locales/en/learn/from-work-to-retirement.json
frontend/public/locales/en/learn/planning-to-save-for-retirement.json
frontend/public/locales/en/learn/retirement-income-sources.json
frontend/public/locales/en/learn/rule-of-thumb-public-pensions.json
frontend/public/locales/en/learn/when-to-take-your-pensions.json
frontend/public/locales/en/quiz/tasks.json
frontend/public/locales/fr/home.json
frontend/public/locales/fr/learn.json
frontend/public/locales/fr/learn/from-work-to-retirement.json
frontend/public/locales/fr/learn/planning-to-save-for-retirement.json
frontend/public/locales/fr/learn/retirement-income-sources.json
frontend/public/locales/fr/learn/rule-of-thumb-public-pensions.json
frontend/public/locales/fr/learn/when-to-take-your-pensions.json
frontend/public/locales/fr/quiz/tasks.json
frontend/src/components/ApplicationNameBar.tsx
frontend/src/components/Breadcrumb.tsx
frontend/src/components/Header.tsx
frontend/src/components/Layout.tsx
frontend/src/components/LearnPageLayout.tsx
frontend/src/pages/home.tsx
frontend/src/pages/learn/from-work-to-retirement.tsx
frontend/src/pages/learn/index.tsx
frontend/src/pages/learn/planning-to-save-for-retirement.tsx
frontend/src/pages/learn/retirement-income-sources.tsx
frontend/src/pages/learn/rule-of-thumb-public-pensions.tsx
frontend/src/pages/learn/when-to-take-your-pensions.tsx
frontend/src/pages/quiz/tasks/[[...filters]].tsx

- Switched back to custom breadcrumbs stored in the locale files
- Breadcrumbs are then mapped into Layout props in order to produce the key output if errors occur
- Small adjustments to ApplicationNameBar to align with Figma
- Try each page and confirm breadcrumbs are appearing as per designs

AB#343 Finalize Breadcrumbs

---

frontend-tests/README.md
frontend-tests/cypress/e2e/Desktop/Test130.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test133.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test154.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test155.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test156.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test157.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test160.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test162.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test163.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test220.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test221.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test260.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test261.spec.cy.js
frontend-tests/cypress/e2e/Desktop/Test268.spec.cy.js
frontend-tests/cypress/e2e/Mobile/Test207.spec.cy.js
frontend-tests/cypress/e2e/Mobile/Test213.spec.cy.js
frontend-tests/cypress/e2e/Mobile/Test214.spec.cy.js
frontend-tests/cypress/e2e/Mobile/Test215.spec.cy.js
frontend-tests/cypress/e2e/Mobile/Test217.spec.cy.js
frontend-tests/cypress/e2e/Mobile/Test228.spec.cy.js
frontend-tests/cypress/e2e/Mobile/Test307.spec.cy.js
frontend-tests/cypress/support/Utility.js
frontend-tests/cypress/support/commands.js

fix insert spy on dom api - guarantees that the test runner only starts when the application is ready to process the change event. insert for each test file.
fix test 130 to include path assertions
fix test 133 to remove tests
fix test 268 breadcrumb test to remove page title assert
insert new language method in utility file for click true

AB#130 AB#133 AB#268 Eh/insert test 130 133 268. Also insert spy on dom api

---

frontend-tests/cypress/e2e/Desktop/Test319.spec.cy.js
frontend-tests/cypress/e2e/Mobile/Test328.spec.cy.js

[ADO-319](https://dev.azure.com/JourneyLab/SeniorsJourney/_workitems/edit/319)
[ADO-328](https://dev.azure.com/JourneyLab/SeniorsJourney/_workitems/edit/328)
Description
Test page https://seniors-journey-test.dev-dp.dts-stn.com/en/learn/retirement-income-sources
List tests for mobile test 328 and test desktop test 319
- Left menu and items visible screen sizes tests
- Scroll screen sizes tests
- Left menu items are clickable screen size tests
- test one link url pathname

AB#319 AB#328 insert test 319 328

---

frontend/src/components/Banner.tsx
frontend/tailwind.config.js

[frontend] fix tailwind border color

---

frontend/src/components/AlertCard.tsx
frontend/src/pages/learn/when-to-take-your-pensions.tsx

- set table style to be reponsive

[frontend] set table reponsive

---

frontend/src/components/LearnPageLayout.tsx
frontend/src/pages/learn/from-work-to-retirement.tsx
frontend/src/pages/learn/planning-to-save-for-retirement.tsx
frontend/src/pages/learn/retirement-income-sources.tsx
frontend/src/pages/learn/rule-of-thumb-public-pensions.tsx
frontend/src/pages/learn/when-to-take-your-pensions.tsx

- remove Learn More from LearnPageLayout

[frontend] remove Learn More from LearnPageLayout

---

frontend/public/locales/en/learn/retirement-income-sources.json
frontend/public/locales/en/learn/when-to-take-your-pensions.json
frontend/public/locales/fr/learn/retirement-income-sources.json
frontend/public/locales/fr/learn/when-to-take-your-pensions.json
frontend/src/components/AccessibilityGraphContainer.tsx
frontend/src/components/AccessibilityTable.tsx
frontend/src/pages/learn/retirement-income-sources.tsx
frontend/src/pages/learn/when-to-take-your-pensions.tsx

Add some ARIA to assist screen readers.

add a11y tweaks

---

frontend/src/components/quiz/QuizDialog.tsx
frontend/src/pages/_app.tsx

- store quiz data when user submit

[frontend] store quiz data when user submit

---

frontend/src/components/quiz/QuizDialog.tsx

Add aria attribute and ids to remove the following:

add aria and ids to quiz modal

---

frontend/src/pages/quiz/tasks/[[...filters]].tsx

Remove answers and tags sections which were only put in for visual debugging.

remove debugging ui features

---

frontend-tests/cypress/e2e/Desktop/Test260.spec.cy.js

[ADO-260](https://dev.azure.com/JourneyLab/SeniorsJourney/_workitems/edit/260)
Description
Test learn overview - Explore our Content - Making Retirement decision
- test links exists on cards
- test with English and French

AB#260 committing RG-Test260 to dev

---

frontend/src/data/tasks.json

Task list content updated by designer directly into tasks.json
- 23 task titles and 2 description changes in the before retirement section
-  5 task titles changes in the apply section
- npm i
- npm run dev
- run the quiz

task list content updated by designer

---

frontend/public/locales/en/learn/case-studies/bonnie.json
frontend/public/locales/en/learn/case-studies/fred.json
frontend/public/locales/en/learn/case-studies/keith.json
frontend/public/locales/fr/learn/case-studies/bonnie.json
frontend/public/locales/fr/learn/case-studies/fred.json
frontend/public/locales/fr/learn/case-studies/keith.json
frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/fred.tsx
frontend/src/pages/learn/case-studies/keith.tsx

Add file structure for the case studies

[frontend] add case study file structure

---

frontend/public/locales/en/learn.json
frontend/public/locales/fr/learn.json

[frontend] fix broken image link

---

frontend/src/pages/checklist/[filters].tsx

[frontend] fix checklist header i18n

---

infrastructure/terragrunt/nonprod/oauth-proxy-aad-application/terragrunt.hcl

Add the staging URL to the Azure AD OAuth callback list.

[infrastructure] Add staging to AAD callbacks

---

gitops/environments/staging/.env.seniors-journey-frontend-auth.sample
gitops/environments/staging/.env.seniors-journey-frontend.sample
gitops/environments/staging/deployments.patch.yaml
gitops/environments/staging/ingresses.yaml
gitops/environments/staging/kustomization.yaml
gitops/environments/staging/oauth-proxy.cfg
gitops/environments/staging/services.patch.yaml

- adding staging files to gitops folder... for gitops

adding stage env to gitops

---

frontend/public/locales/en/learn/deciding-when-to-collect-public-pensions.json
frontend/public/locales/fr/learn/deciding-when-to-collect-public-pensions.json
frontend/src/pages/learn/deciding-when-to-collect-public-pensions.tsx

Fix styling on alerts and cleanup some translations.

[frontend] add bold to alert

---

frontend/src/pages/home.tsx

- fix banner spacing by adding margin bottom

[frontend] fix banner spacing

---

frontend/src/pages/learn/deciding-when-to-collect-public-pensions.tsx

Resolve overflow issue on smaller viewports.

[frontend] add overflow control to table

---

frontend/src/components/HeroBanner.tsx
frontend/src/pages/home.tsx
frontend/src/pages/learn/index.tsx

[frontend] add HeroBanner component

---

frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/fred.tsx
frontend/src/pages/learn/case-studies/keith.tsx
frontend/src/pages/learn/deciding-when-to-collect-public-pensions.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx
frontend/src/pages/learn/planning-to-save-for-retirement.tsx

- normalize Key Takeaways lists style

[frontend] normalize Key Takeaways lists

---

frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/src/pages/home.tsx

- Implemented French translations
- Removed unused json content
- Fixed some json structures (unnecessary arrays, that sort of thing)

implemented french translations, and corrected some json structures

---

frontend/public/locales/en/home.json

home translation english to match mock up

change home english translations

---

frontend/public/locales/fr/home.json
frontend/src/pages/home.tsx

- fixes a broken key
- fixes incorrect urls

correcting misnamed url key, fixing urls for french translation

---

frontend/__tests__/components/ApplicationNameBar.test.tsx
frontend/src/components/ApplicationNameBar.tsx
frontend/src/components/Header.tsx

- move useChecklistUrl hook to Header (code refactoring)

[frontend] move useChecklistUrl hook to Header

---

frontend/public/locales/fr/learn/deciding-when-to-collect-public-pensions.json
frontend/public/locales/fr/learn/main-sources-of-retirement-income.json
frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/fred.tsx
frontend/src/pages/learn/case-studies/keith.tsx
frontend/src/pages/learn/deciding-when-to-collect-public-pensions.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx

- use t function with string literal
- add French missing key-takeaways

[frontend] Fix translation

---

frontend/public/locales/en/learn/case-studies/fred.json
frontend/public/locales/fr/learn/case-studies/fred.json
frontend/src/pages/learn/case-studies/fred.tsx

Update Fred case study to match mock ups
- page content
Awaiting translations.

[frontend] Quality Control Fred Case Study

---

gitops/environments/dev/deployments.patch.yaml
gitops/environments/staging/deployments.patch.yaml
gitops/environments/test/deployments.patch.yaml

- setup AA staging script
- bump Staging to version `20230519-0186-6a0dc4ae`

[gitops] setup AA staging script

---

frontend/src/pages/_document.tsx

- Fix AA CSP headers.. just like the title says.

Fix AA CSP headers

---

gitops/environments/staging/deployments.patch.yaml

- updated staging frontend to 20230519-0187-9c8fa83c

[gitops] updated staging frontend to 20230519-0187-9c8fa83c

---

frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json

- Changed the international contact us links

corrected international contact us links

---

frontend/src/components/ApplicationNameBar.tsx

- fix checklist button placement to match mockups

[frontend] fix checklist button placement

---

frontend/public/locales/en/learn/case-studies/keith.json
frontend/public/locales/fr/learn/case-studies/keith.json
frontend/src/pages/learn/case-studies/keith.tsx

- modify content to match mock ups
Awaiting translations

[frontend] Quality Control Keith Case Study

---

frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/src/pages/home.tsx

- remove Telephone and TTY links (as per mockups and Canada website)

[frontend] remove Telephone and TTY links

---

frontend/public/locales/en/learn/rules-of-thumb-for-public-pensions.json
frontend/public/locales/fr/learn/rules-of-thumb-for-public-pensions.json
frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx

Page re-write to match mock ups
Awaiting translations

[frontend] Quality Control Rules of Thumb for Public Pensions

---

frontend/public/locales/en/learn.json
frontend/public/locales/fr/learn.json
frontend/src/pages/learn/index.tsx

- learn page refactoring
- remove duplicate static content like href, image url and min read info in JSON locales
- move away of array in JSON locales

[frontend] learn page refactoring

---

gitops/environments/dev/deployments.patch.yaml
gitops/environments/test/deployments.patch.yaml

- remove AA config from dev and test since only staging will be whitelisted

[gitops] remove AA config from dev and test

---

frontend/public/locales/en/quiz.json
frontend/public/locales/fr/quiz.json
frontend/src/components/quiz/QuizDialog.tsx
frontend/src/components/quiz/questions/QuestionApply.tsx
frontend/src/components/quiz/questions/QuestionDisabilityBenefits.tsx
frontend/src/components/quiz/questions/QuestionEarn.tsx
frontend/src/components/quiz/questions/QuestionFeelPrepared.tsx
frontend/src/components/quiz/questions/QuestionHowLong.tsx
frontend/src/components/quiz/questions/QuestionStatus.tsx
frontend/src/components/quiz/questions/QuestionWhen.tsx
frontend/src/components/quiz/questions/QuestionWhere.tsx

- remove `id` and `value` from i18n file since they shouldn't be translated

[frontend] quiz refactoring

---

frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/src/pages/home.tsx

- remove `"id"` from i18n local since they shouldn't be translated
- remove `"url"` from i18n when it's an relative application url and it shouldn't be translated
- move away array in i18n files
- remove unused i18n keys

[frontend] home i18n refactoring

---

frontend/src/pages/checklist/[filters].tsx

- **_always_** return tasks with answer's value all

[frontend] tasks with answer's value all

---

frontend/src/pages/home.tsx

Prevent overflow on home page.

[frontend] remove whitespace-nowrap to prevent overflow

---

frontend/public/locales/en/learn/planning-to-save-for-retirement.json
frontend/public/locales/fr/learn/planning-to-save-for-retirement.json
frontend/src/pages/learn/planning-to-save-for-retirement.tsx

Aligns page with mock up
Awaiting translations

[frontend] quality control saving for retirement page

---

frontend/public/locales/en/common.json
frontend/public/locales/fr/common.json

[frontend] sort common locale JSON

---

frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/src/pages/home.tsx

[frontend] sort home locale JSON

---

frontend/public/locales/en/learn.json
frontend/public/locales/fr/learn.json

[frontend] sort learn locale JSON

---

frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/fred.tsx
frontend/src/pages/learn/case-studies/keith.tsx
frontend/src/pages/learn/deciding-when-to-collect-public-pensions.tsx

Remove <Img /> and revert to Next Image.

[frontend] revert custom Img component to Next Image

---

frontend/public/locales/en/quiz.json
frontend/public/locales/fr/quiz.json

- add missing Quiz seo metatag

[frontend] add missing seo metatag

---

frontend/public/locales/en/learn/case-studies/bonnie.json
frontend/public/locales/fr/learn/case-studies/bonnie.json
frontend/src/pages/learn/case-studies/bonnie.tsx

Remove relative paths from locales and put in source.

[frontend] cleanup relative paths on bonnie case study

---

gitops/environments/staging/kustomization.yaml

Add AA configuration to staging

---

gitops/environments/staging/deployments.patch.yaml
gitops/environments/staging/kustomization.yaml

[gitops] Fix Adobe Analytics

---

gitops/environments/staging/deployments.patch.yaml

[gitops] Update frontend version

---

frontend/src/data/tasks.json

- use Hyphen `-` instead of En dash `–`

[frontend] use Hyphen instead of En dash

---

frontend/public/locales/en/learn/going-from-work-to-retirement.json
frontend/public/locales/fr/learn/going-from-work-to-retirement.json
frontend/src/pages/learn/going-from-work-to-retirement.tsx

Page re-write  for /learn/going-from-work-to-retirment

[frontend] quality control going from work to reitrement page

---

frontend/src/components/quiz/QuizDialog.tsx
frontend/src/components/quiz/questions/QuestionApply.tsx
frontend/src/components/quiz/questions/QuestionDisabilityBenefits.tsx
frontend/src/components/quiz/questions/QuestionEarn.tsx
frontend/src/components/quiz/questions/QuestionFeelPrepared.tsx
frontend/src/components/quiz/questions/QuestionHowLong.tsx
frontend/src/components/quiz/questions/QuestionStatus.tsx
frontend/src/components/quiz/questions/QuestionWhen.tsx
frontend/src/components/quiz/questions/QuestionWhere.tsx
frontend/src/lib/types.ts
frontend/src/theme.ts

- use [LoadingButton ](button) when submitting the quiz
- refactoring logic and style of all Question components
This PR wwitch custom ToggleButton style to MUI default style. The current style is identical to a regular MUI Button and it's confusing. 
https://mui.com/material-ui/react-toggle-button/

[frontend] quiz dialog refactoring

---

frontend/public/locales/en/common.json
frontend/public/locales/fr/common.json

- remove unused keys in common locale

[frontend] remove unused keys in common locale

---

frontend/public/locales/en/learn/case-studies/keith.json
frontend/public/locales/fr/learn/case-studies/keith.json

[frontend] add missing heading

---

frontend/src/data/tasks.json

Fix task contents' null display order and fix markdown links 
- Replace `"displayOrder": null` with a numeric value
- Fixed broken markdown link syntax
- remove orphan brackets
- npm i
- npm run dev
- Answer quiz and review "all" and answers relating to "Receiving benefits" sections
- In French, Section `Lors de la demande de prestation` section, answer key "all" check title `(Attendre l'avis de décision relative à votre pension de la SV` changed to `Attendre l'avis de décision relative à votre pension de la SV`
- In French, Section `Lors de la demande de prestation`, task title `Décider du montant à prélever chaque mois sur votre ou vos pensions privées ou sur d'autres formes d'épargne` check more resource  `(Supplément de revenu garanti Aperçu` changed to …

add display order value, fixed links and text

---

gitops/environments/dev/.env.seniors-journey-frontend.sample
gitops/environments/staging/.env.seniors-journey-frontend.sample
gitops/environments/test/.env.seniors-journey-frontend.sample

Update sample .env files

---

frontend/src/components/NestedAccordion.tsx

This PR is intended to fix the issue having additional spacing being added in the y-axis accordions when they are expanded.

[frontend]  prevent addtional spacing on accordian expand

---

frontend/.env.example
frontend/__mocks__/next/config.ts
frontend/__tests__/pages/api/readyz.test.ts
frontend/next.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/BreadcrumbStructuredData.tsx
frontend/src/components/Header.tsx
frontend/src/lib/hooks/useChecklistUrl.ts
frontend/src/lib/hooks/usePublicRuntimeConfig.ts
frontend/src/lib/schemas/public-runtime-config-schema.ts
frontend/src/lib/types.ts
frontend/src/next-seo.config.ts
frontend/src/pages/_app.tsx
frontend/src/pages/api/readyz.ts
frontend/src/pages/home.tsx
gitops/environments/dev/deployments.patch.yaml
gitops/environments/staging/deployments.patch.yaml
gitops/environments/test/deployments.patch.yaml

Issues: #274 & #275 
- add public runtime config validation (espacially for required variable `NEXT_PUBLIC_APP_BASE_URI`) 
- use `urlcat` to build URLs, give flexibiliy with `NEXT_PUBLIC_APP_BASE_URI` variable to end with or without slash `/`
- add public runtime config validation at `/api/readyz` for k8s readiness
Set your `.env.local` variable `NEXT_PUBLIC_APP_BASE_URI` with `http://example.com` and run the application. If ommited or bad URL the application will throw an error.
https://github.com/balazsbotond/urlcat

Public runtime config validation

---

gitops/environments/staging/deployments.patch.yaml

- update staging to 20230530-0229-768645f2

[gitops] update staging to 20230530-0229-768645f2

---

frontend/public/locales/en/checklist.json
frontend/public/locales/en/common.json
frontend/public/locales/fr/checklist.json
frontend/public/locales/fr/common.json
frontend/src/components/InputLabel.tsx

- remove unused keys
- sort keys
- fix `useTranslation` call with namespace missing

[frontend] refactor translation

---

frontend/src/data/tasks.json

- fix ISP1603OAS form details link (French)

[frontend] fix ISP1603OAS form details link

---

infrastructure/terragrunt/nonprod/oauth-proxy-aad-application/terragrunt.hcl

- Add production OAuth callbacks to AAD OAuth client

[infrastructure] Add production OAuth callbacks

---

frontend/src/data/tasks.json

Fix tasks links

---

frontend/public/locales/en/quiz.json
frontend/public/locales/fr/quiz.json
frontend/src/components/quiz/QuizDialog.tsx

- fix MUI LoadingButton warning

[frontend] fix MUI LoadingButton warning

---

gitops/environments/dev/deployments.patch.yaml
gitops/environments/dev/kustomization.yaml
gitops/environments/production/deployments.patch.yaml
gitops/environments/production/ingresses.yaml
gitops/environments/production/kustomization.yaml
gitops/environments/production/oauth-proxy.cfg
gitops/environments/staging/deployments.patch.yaml
gitops/environments/staging/kustomization.yaml
gitops/environments/test/deployments.patch.yaml
gitops/environments/test/kustomization.yaml

- Reconfigure all environments for Adobe Analytics
- Reconfigure production environment to use correct DNS name

[gitops] Reconfigure all environments for AA

---

frontend/public/locales/en/quiz.json
frontend/public/locales/fr/quiz.json

- fix Question 1 option-after-70 text (as per mockup)

[frontend] fix Question 1 option-after-70 text

---

gitops/environments/production/deployments.patch.yaml

[gitops] Fix prod application version

---

frontend/public/locales/fr/learn/rules-of-thumb-for-public-pensions.json
frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx

- fix key takeaways link
`secondary` prop accepts a ReactNode then it can be anything.
https://mui.com/material-ui/api/list-item-text/#props

[frontend] fix key takeaways link

---

frontend/public/locales/en/checklist.json
frontend/public/locales/fr/checklist.json
frontend/src/pages/checklist/[filters].tsx

[frontend] checklist translations

---

frontend/public/locales/fr/home.json
frontend/public/locales/fr/learn/case-studies/keith.json
frontend/public/locales/fr/learn/going-from-work-to-retirement.json
frontend/public/locales/fr/learn/planning-to-save-for-retirement.json
frontend/public/locales/fr/learn/rules-of-thumb-for-public-pensions.json
frontend/src/data/tasks.json

- remove space after apostrophe

[frontend] remove space after apostrophe

---

frontend/public/locales/en/learn/going-from-work-to-retirement.json
frontend/public/locales/fr/learn/going-from-work-to-retirement.json
frontend/src/pages/learn/going-from-work-to-retirement.tsx

Quality control changes based on the design team.

[frontend] QC going from work to retirement

---

frontend/src/data/tasks.json

- fix task links (duplicate French links)

[frontend] fix task links

---

frontend/public/locales/en/learn/rules-of-thumb-for-public-pensions.json
frontend/public/locales/fr/learn/rules-of-thumb-for-public-pensions.json
frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx

Quality control based on the design team's review.

[frontend] qc rules of thumb for public pensions page

---

frontend/src/pages/home.tsx

- Updated the mobile UI for the Home page tab system so that the designs are more consistent with the desktop version
- Tab text is now dynamic with what tab is being displayed

Fixed Home Tab Mobile View UI

---

frontend/src/components/NestedAccordion.tsx

Changed styles to get accordion back to original specs per mock up
How it looks:

[frontend] accordion border and padding

---

frontend/src/pages/learn/deciding-when-to-start-your-public-pensions.tsx

[frontend] fix fred link

---

frontend/public/locales/en/common.json
frontend/public/locales/fr/common.json

Footer text changes from QC

---

frontend/public/locales/en/common.json
frontend/public/locales/en/home.json
frontend/public/locales/en/learn.json
frontend/public/locales/en/learn/going-from-work-to-retirement.json
frontend/public/locales/fr/common.json
frontend/public/locales/fr/home.json
frontend/public/locales/fr/learn.json
frontend/public/locales/fr/learn/going-from-work-to-retirement.json
frontend/src/components/Layout.tsx
frontend/src/pages/_app.tsx
frontend/src/pages/home.tsx
frontend/src/pages/learn/going-from-work-to-retirement.tsx
frontend/src/pages/learn/index.tsx

- rename `when-to-collect` i18next key to `when-to-start`

[frontend] rename when-to-collect i18next key

---

frontend/package-lock.json
frontend/package.json

[frontend] bump dependencies

---

frontend/public/locales/fr/learn/main-sources-of-retirement-income.json

Small PR to insert semicolons where requested in lists and to also fix some typos based on the design team's comments.

[frontend] add semicolons to flagged lists and fix typo

---

frontend/public/locales/en/learn/deciding-when-to-start-your-public-pensions.json
frontend/public/locales/en/learn/going-from-work-to-retirement.json
frontend/public/locales/en/learn/main-sources-of-retirement-income.json
frontend/public/locales/fr/learn/deciding-when-to-start-your-public-pensions.json
frontend/public/locales/fr/learn/going-from-work-to-retirement.json
frontend/public/locales/fr/learn/main-sources-of-retirement-income.json

[frontend] sort locale JSON

---

frontend/public/locales/fr/learn.json
frontend/public/locales/fr/learn/going-from-work-to-retirement.json

Changes to french locales for the learning page banner and going from work to retirement page, based on the design team's comments.

[frontend] french text changes

---

frontend/public/locales/fr/home.json
frontend/src/pages/home.tsx

- French text changes
- some CSS changes to match padding/spacing in figma (for plan/apply tabs)

Landing page text and structure changes from QC

---

frontend/public/locales/en/learn/case-studies/fred.json
frontend/public/locales/fr/learn/case-studies/fred.json

Changes to the locales in Fred's case study per design team comments.

[frontend] change fred case study locales

---

frontend/public/locales/en/quiz.json
frontend/public/locales/fr/quiz.json
frontend/src/components/quiz/QuizDialog.tsx
frontend/src/components/quiz/questions/QuestionApply.tsx
frontend/src/components/quiz/questions/QuestionDisabilityBenefits.tsx
frontend/src/components/quiz/questions/QuestionEarn.tsx
frontend/src/components/quiz/questions/QuestionFeelPrepared.tsx
frontend/src/components/quiz/questions/QuestionHowLong.tsx
frontend/src/components/quiz/questions/QuestionStatus.tsx
frontend/src/components/quiz/questions/QuestionWhen.tsx
frontend/src/components/quiz/questions/QuestionWhere.tsx
frontend/src/pages/quiz.tsx

- Removed capitalization in title
- Changed font to match spec
- Remove "question" across quiz
- Removed outline for previous button
- Remove button icons
- Switched choice order
- Underlined "more" and "less"
- Updated text
- Min height on confirmation modal

QC Quiz Changes

---

frontend/public/locales/fr/learn/main-sources-of-retirement-income.json

Same as title.  These are changes based on the Figma mockup.

[frontend] fix typos in main sources of income page

---

frontend/src/components/ErrorSummary.tsx
frontend/src/components/Markdown.tsx
frontend/src/components/TaskCard.tsx
frontend/src/components/error-pages/Error404Page.tsx
frontend/src/components/error-pages/ErrorPage.tsx
frontend/src/pages/home.tsx
frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/keith.tsx
frontend/src/pages/learn/going-from-work-to-retirement.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx
frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx

[frontend] standardize list styles

---

frontend/src/components/AccessibilityGraphContainer.tsx

- Made the case study dropdowns clickable

Make the case study dropdowns clickable

---

frontend/package-lock.json
frontend/package.json
frontend/src/data/tasks-schema.json
frontend/src/data/tasks-validation.ts
frontend/src/data/tasks.json

- add tasks json schema
- add [Ajv JSON schema validator](https://ajv.js.org/)

[frontend] add tasks json schema

---

frontend/src/pages/_error.tsx

- catch and log errors on server side
https://github.com/vercel/next.js/discussions/32230#discussioncomment-3149711

[frontend] catch and log errors on server side

---

frontend/src/pages/learn/deciding-when-to-start-your-public-pensions.tsx

- fix key-takeaways logic (`primary` and `secondary` are type of `ReactNode`)

[frontend] fix key-takeaways logic

---

frontend/public/locales/fr/learn/case-studies/bonnie.json
frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/fred.tsx
frontend/src/pages/learn/case-studies/keith.tsx
frontend/src/pages/learn/deciding-when-to-start-your-public-pensions.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx

- pass object to tableData prop (explicit)
- fix french typo `pluse` => `plus`

[frontend] pass object to tableData prop

---

frontend/src/data/tasks.json

Change casing to resolve the following:

[frontend] change casing

---

frontend/public/locales/en/checklist.json
frontend/public/locales/en/learn/main-sources-of-retirement-income.json
frontend/public/locales/fr/checklist.json
frontend/public/locales/fr/learn/main-sources-of-retirement-income.json

- sort and remove unused i18next keys

[frontend] sort and remove unused i18next keys

---

frontend/public/locales/en/learn.json
frontend/src/pages/home.tsx
frontend/src/pages/learn/index.tsx

- Rahul requested some changes to the intial qc fixes:
- Keith Blurb returns to "Post-Retirement Benefits"
- Padding fixes on the cards
- Font increase on the contact button

QC Learn Page Tweaks

---

frontend/public/locales/fr/learn/deciding-when-to-start-your-public-pensions.json

- Updated the French Fred Learn More Text on Deciding When to take public pensions page

AB#486 Update Fred Learn More Text

---

frontend/public/locales/fr/learn.json

Update Fred's Case Study card on the learn page.

[frontend] update fred learn card text

---

frontend/src/components/HeroBanner.tsx
frontend/src/components/quiz/QuizDialog.tsx
frontend/src/pages/checklist/[filters].tsx

- Updated Quiz Dialog Spacing to match Figma
- Bolding on Quiz Dialog Buttons
- Matched checklist header height with Figma

QC Updated Quiz Spacing and Checklist Header

---

frontend/public/locales/en/learn/case-studies/fred.json
frontend/public/locales/fr/learn/case-studies/fred.json

And [ADO-489](https://dev.azure.com/JourneyLab/SeniorsJourney/_workitems/edit/489)
- changed text for EN chart description
- changed text for paragraph under chart in FR

QC for chart text elements

---

frontend/public/locales/fr/quiz.json

Address the following text changes:

[frontend] update quiz disclaimer text in french

---

frontend/public/locales/fr/home.json

QC for Homepage Text Changes

---

frontend/public/locales/en/quiz.json
frontend/public/locales/fr/quiz.json

More text changes from the design team.

[frontend] quiz text changes

---

frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/fred.tsx
frontend/src/pages/learn/case-studies/keith.tsx
frontend/src/pages/learn/deciding-when-to-start-your-public-pensions.tsx
frontend/src/pages/learn/going-from-work-to-retirement.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx
frontend/src/pages/learn/planning-to-save-for-retirement.tsx
frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx

- Adding underline for Learn more titles

QC for Many Pages, Adding Underline for Learn More Titles

---

gitops/environments/production/deployments.patch.yaml
gitops/environments/staging/deployments.patch.yaml

- bump STAGING and PROD frontends

Bump environments

---

frontend/src/data/tasks.json

Address text changes per design team:

[frontend] update data.json text

---

frontend/__tests__/components/TaskCard.test.tsx
frontend/src/pages/checklist/[filters].tsx
frontend/src/pages/home.tsx
frontend/src/pages/index.tsx
frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/fred.tsx
frontend/src/pages/learn/case-studies/keith.tsx
frontend/src/pages/learn/deciding-when-to-start-your-public-pensions.tsx
frontend/src/pages/learn/going-from-work-to-retirement.tsx
frontend/src/pages/learn/index.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx
frontend/src/pages/learn/planning-to-save-for-retirement.tsx
frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx
frontend/src/pages/quiz.tsx
frontend/src/utils/seo-utils.ts

- unilingual dcterms title
- fix TS unit test

Unilingual dcterms title

---

gitops/environments/production/deployments.patch.yaml
gitops/environments/staging/deployments.patch.yaml

[gitops] Bump staging prod

---

frontend/public/robots.txt
frontend/src/middleware.ts

- add robots.txt file
https://nextjs.org/learn/seo/crawling-and-indexing/robots-txt

[frontend] add robots.txt file

---

frontend/src/pages/home.tsx

- Add underlines to the links of the Apply Tab

QC for Homepage Apply Tab Underlined Links

---

frontend/src/pages/checklist/[filters].tsx

The restart button and print button need to bold, per the mock ups.  This PR addresses that.

[frontend] bold restart and print butttons

---

frontend/src/pages/_document.tsx

- Change `'default-src': ["'none'"]` to `'default-src': ["'self'"]`.

[frontend] Fix broken CSP

---

gitops/environments/production/deployments.patch.yaml

I have a little update
That I want to share with you
It's about the Retirement Hub
And what we're going to do
We're bumping up the version
To make it shiny and new
We've fixed some bugs and added features
And improved the UI too
So please review this pull request
And let me know what you think
Don't be too harsh or critical
Or I might need a drink 🍻

[gitops] Bump prod to 20230615-0130-d8425d4c

---

frontend/public/locales/fr/learn/case-studies/keith.json

QC for Keith, Text Change

---

frontend/src/components/HeroBanner.tsx
frontend/src/pages/learn/index.tsx

- set images sizes prop images are using fill prop
https://nextjs.org/docs/app/api-reference/components/image#sizes

[frontend] set images sizes prop

---

frontend/public/locales/fr/learn/case-studies/keith.json

- Text changes under the graphs

QC for Keith, Text Changes for Choices

---

frontend/src/pages/learn/case-studies/keith.tsx

[frontend] fix Trans component usage

---

frontend/public/locales/fr/learn/deciding-when-to-start-your-public-pensions.json

Update table header to proper text based on the design team's request:

[frontend] change table column text in french

---

frontend/public/locales/en/learn/case-studies/fred.json
frontend/public/locales/fr/learn/case-studies/fred.json

QCv2 for Fred, FR/EN text changes

---

frontend/src/components/TableOfContents.tsx

- fix TOC items style to match mockups

[frontend] fix TOC items style

---

frontend/public/locales/en/learn/going-from-work-to-retirement.json

- fix second career content based on Figma's comment
https://www.figma.com/file/fBuLkbEjrAiZSF1gO6SSQq?node-id=3804:96720#475792694

[frontend] fix second career content

---

frontend/src/pages/learn/index.tsx

- Added a box-shadow to the learn cards on hover, had to tweak the transition duration as it was causing a weird flickering effect.
- Open to thoughts

Learn Card Hover Effect

---

frontend/public/locales/fr/home.json
frontend/public/locales/fr/learn/main-sources-of-retirement-income.json
frontend/src/data/tasks.json

- fix Canadian Retirement Income Calculator by removing the acronym

[frontend] fix Canadian Retirement Income Calculator

---

frontend/src/components/AccessibilityGraphContainer.tsx
frontend/src/components/LearnPageLayout.tsx
frontend/src/pages/checklist/[filters].tsx
frontend/src/pages/home.tsx
frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/fred.tsx
frontend/src/pages/learn/case-studies/keith.tsx
frontend/src/pages/learn/deciding-when-to-start-your-public-pensions.tsx
frontend/src/pages/learn/going-from-work-to-retirement.tsx
frontend/src/pages/learn/index.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx
frontend/src/pages/learn/planning-to-save-for-retirement.tsx
frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx
frontend/src/pages/quiz.tsx
frontend/src/styles/globals.css

- refactor responsive headings to match mockups
- refactor responsive headings in pages for consistency
Figma Responsive Headings
https://www.figma.com/file/S8YVqN48jDROKAv4jlZN2w/Seniors-Journey-Lab-Material-2?type=design&node-id=242-26836&t=NLl4vVOigp4VHM49-4

[frontend] refactor responsive headings

---

frontend/public/locales/en/common.json
frontend/public/locales/en/home.json
frontend/public/locales/en/learn/going-from-work-to-retirement.json
frontend/public/locales/en/learn/main-sources-of-retirement-income.json
frontend/public/locales/en/learn/planning-to-save-for-retirement.json

Content changes to EN homepage, footer, main sources, planning, going from work to retirement

---

frontend/public/locales/fr/home.json
frontend/public/locales/fr/learn/case-studies/fred.json
frontend/public/locales/fr/learn/case-studies/keith.json
frontend/public/locales/fr/learn/main-sources-of-retirement-income.json

- update oas estimator French links

[frontend] update oas estimator French links

---

frontend/public/locales/en/learn/rules-of-thumb-for-public-pensions.json
frontend/public/locales/fr/learn/rules-of-thumb-for-public-pensions.json
frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx

Add missing GIS link to locales on the rules of thumb page.

[frontend] add missing GIS link

---

frontend/public/locales/en/quiz.json
frontend/public/locales/fr/quiz.json
frontend/src/components/quiz/questions/QuestionWhere.tsx

Remove underlines from quiz questions.  
Per:

[frontend] remove underline from quiz question

---

frontend/public/locales/en/learn/case-studies/fred.json
frontend/public/locales/en/learn/case-studies/keith.json

- fix OAS benefits estimator links
Figma's related comments.
https://www.figma.com/file/fBuLkbEjrAiZSF1gO6SSQq?node-id=4242:120424#475826520
https://www.figma.com/file/fBuLkbEjrAiZSF1gO6SSQq?node-id=4242:129952#475678107

[frontend] fix OAS benefits estimator links

---

frontend/public/locales/fr/learn/rules-of-thumb-for-public-pensions.json

- Rules of thumb has a missing accented a
- Hopefully the last of french learn content changes

AB#503 Missing Accent

---

frontend/src/pages/checklist/[filters].tsx

Modify the checklist page to meet the user acceptance criteria in ticket 502.

[frontend] modify show all tasks logic

---

gitops/environments/staging/deployments.patch.yaml

[gitops] Bump staging version to latest

---

frontend/src/components/quiz/questions/QuestionApply.tsx
frontend/src/theme.ts

- Box Shadows won't appear on Windows High Contrast themes so they aren't great for accessibility, I've swapped them out with outlines instead that do.
- Custom styling on some outlines in order to make them fit well on their containers
Before:
After:

a11y Outline Fix

---

frontend/public/locales/en/learn/case-studies/keith.json
frontend/src/pages/learn/case-studies/keith.tsx

Added new paragraph under the PRB section on Keith's case study page.  This is only applicable to the english version of the site.

[frontend] add new paragraph

---

frontend/src/components/quiz/QuizDialog.tsx
frontend/src/pages/checklist/[filters].tsx

- checklist refactoring with useDeferredValue hook
useDeferredValue Hook Explained
https://blog.webdevsimplified.com/2022-05/use-deferred-value/

checklist refactoring

---

frontend-tests/package-lock.json
frontend-tests/package.json

- bump frontend-tests dependencies

[frontend-tests] bump dependencies

---

frontend/next-i18next.config.js
frontend/src/pages/_app.tsx
frontend/src/pages/checklist/[filters].tsx
frontend/src/pages/home.tsx
frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/fred.tsx
frontend/src/pages/learn/case-studies/keith.tsx
frontend/src/pages/learn/deciding-when-to-start-your-public-pensions.tsx
frontend/src/pages/learn/going-from-work-to-retirement.tsx
frontend/src/pages/learn/index.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx
frontend/src/pages/learn/planning-to-save-for-retirement.tsx
frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx
frontend/src/pages/quiz.tsx

- next-i18next config
Unserializable configs
https://github.com/i18next/next-i18next#unserializable-configs

[frontend] next-i18next config

---

frontend/src/pages/checklist/[filters].tsx
frontend/src/pages/home.tsx
frontend/src/pages/learn/case-studies/bonnie.tsx
frontend/src/pages/learn/case-studies/fred.tsx
frontend/src/pages/learn/case-studies/keith.tsx
frontend/src/pages/learn/deciding-when-to-start-your-public-pensions.tsx
frontend/src/pages/learn/going-from-work-to-retirement.tsx
frontend/src/pages/learn/index.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx
frontend/src/pages/learn/planning-to-save-for-retirement.tsx
frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx
frontend/src/pages/quiz.tsx
frontend/src/utils/next-i18next-utils.ts

- next-i18next serverSideTranslations wrapper

refactor[frontend]: next-i18next serverSideTranslations wrapper

---

gitops/environments/staging/kustomization.yaml

[gitops] Increase AA beacon delay

---

gitops/environments/staging/deployments.patch.yaml

Forgot to add this in last commit.

[gitops] Add AA config to deployment

---

gitops/environments/staging/deployments.patch.yaml

Bumping staging to latest build.

[gitops] Bump staging version

---

gitops/environments/production/deployments.patch.yaml
gitops/environments/production/kustomization.yaml

[gitops] Deploy v1.0.0

---

gitops/environments/staging/deployments.patch.yaml
gitops/environments/staging/kustomization.yaml

[gitops] Deploy v1.0.0 to staging

---

frontend/src/next-seo.config.ts

- fix(frontend): twitter site property
https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#attribution
Employment and Social Development Canada
https://twitter.com/ESDC_GC
Emploi et Développement social Canada
https://twitter.com/EDSC_GC

fix(frontend): twitter site property

---

gitops/applications/seniors-journey-frontend/deployments.yaml

[gitops] Increase memory limits in all environments

---

infrastructure/README.md

[infrastructure] fix typo in README

---

frontend/__tests__/lib/mappers/tasks-group-dto-mapper.test.ts
frontend/src/lib/mappers/tasks-group-dto-mapper.ts
frontend/src/lib/types.ts

- chore(frontend): tasks-group-dto-mapper unit tests

chore(frontend): tasks-group-dto-mapper unit tests

---

gitops/environments/production/ingresses.yaml

- feat(gitops): add internal frontend ingress (prod)

feat(gitops): add internal frontend ingress

---

frontend/package-lock.json

- chore(frontend): npm upgrade dependencies

chore(frontend): npm upgrade dependencies

---

frontend/.env.example
frontend/__mocks__/next/config.ts
frontend/next.config.js
frontend/src/components/BreadcrumbStructuredData.tsx
frontend/src/components/Header.tsx
frontend/src/components/pages/HomePage.tsx
frontend/src/lib/hooks/usePublicRuntimeConfig.ts
frontend/src/lib/schemas/public-runtime-config-schema.ts
frontend/src/logging/log-level.ts
frontend/src/logging/log-util.ts
frontend/src/pages/_app.tsx
frontend/src/pages/_document.tsx
frontend/src/pages/api/readyz.ts
gitops/environments/dev/deployments.patch.yaml
gitops/environments/dev/kustomization.yaml
gitops/environments/production/deployments.patch.yaml
gitops/environments/production/kustomization.yaml
gitops/environments/staging/deployments.patch.yaml
gitops/environments/staging/kustomization.yaml
gitops/environments/test/deployments.patch.yaml
gitops/environments/test/kustomization.yaml

- Fix logger level baking issue
More details from related PR https://github.com/DTS-STN/passport-status/pull/560

Fix logger level baking issue

---

frontend/Dockerfile

- chore(deps): update Node.js Docker image to node:20.10.0-bookworm-slim

chore(deps): update Node.js Docker image to node:20.10.0-bookworm-slim

---

.github/dependabot.yml

- Update dependabot.yml directory

Update dependabot.yml directory

---

frontend/public/locales/en/learn/deciding-when-to-start-your-public-pensions.json
frontend/public/locales/fr/learn/case-studies/fred.json

- numerical values on /learn/deciding-when-to-start-your-public-pensions 
- corrected paragraph on the french /learn/case-studies/fred page 
The values on the pages should change to match the corrections in the commit.

Correcting Values as Requested

---

frontend/public/locales/fr/learn/deciding-when-to-start-your-public-pensions.json

- French numbers were missed with previous PR, should now match engltish
-

Correcting Values as Requested - French

---

frontend/public/locales/en/learn/deciding-when-to-start-your-public-pensions.json
frontend/public/locales/fr/learn/deciding-when-to-start-your-public-pensions.json

- Month corrections
-
Months changed from aprtil - june 2023 to october to december 2024

Correcting Values as Requested - Months

---

gitops/environments/production/deployments.patch.yaml

- deploying previous changes with tagged version

Correcting Values as Requested - Deployment

---

gitops/environments/dev/ingresses.yaml
gitops/environments/production/ingresses.yaml
gitops/environments/staging/ingresses.yaml
gitops/environments/test/ingresses.yaml

- Setup redirects as requested.
currently active on dev.

Adding Requested Redirects to New Site
