frontend/.eslintrc.json
frontend/package-lock.json
frontend/package.json

Add `eslint-config-prettier` as a dev dependency to prevent conflict between ESLint and Prettier.
More information:
- <https://prettier.io/docs/en/integrating-with-linters.html>
- <https://github.com/prettier/eslint-config-prettier>

[frontend] Add `eslint-config-prettier`

---

frontend/__tests__/components/ApplicationNameBar.test.tsx
frontend/__tests__/components/Breadcrumb.test.tsx
frontend/public/locales/en/common.json
frontend/public/locales/en/learn.json
frontend/public/locales/fr/common.json
frontend/public/locales/fr/learn.json
frontend/src/components/Breadcrumb.tsx
frontend/src/components/Header.tsx
frontend/src/components/Layout.tsx
frontend/src/pages/_app.tsx
frontend/src/pages/_error.tsx
frontend/src/pages/home.tsx
frontend/src/pages/home/learn.tsx
frontend/src/pages/learn.tsx
frontend/src/styles/globals.css
frontend/tailwind.config.js

- Added Breadcrumb component and Unit Test
- Added "Learn" page to display the component
- Breadcrumbs are automatically generated through React Router. This will only generate breadcrumbs for pages with sub-routes ex. /en/home/learn will have breadcrumbs while /en/learn will not (this can be revisited)
- Error pages were not getting server side translations, this has been resolved
- Pulled this in for Sprint 2

AB#90 Breadcrumb Component

---

frontend/.prettierrc

- Fix prettier-plugin-tailwindcss installation
I noticed when running prettier on a file that `prettier-plugin-tailwindcss` wasn't applied. I added the plugins to Prettier config explicitly and it fixed the issue.
https://github.com/tailwindlabs/prettier-plugin-tailwindcss
Automatic Class Sorting with Prettier
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

fix prettier-plugin-tailwindcss installation

---

frontend/next.config.js

Removing unnecessary `X-Powered-By` response header (found by OWASP ZAP scan).

Remove X-Powered-By header (OWASP ZAP warning)

---

frontend/src/pages/_app.tsx
frontend/src/pages/home.tsx
frontend/src/pages/learn/index.tsx
frontend/src/pages/learn/retirement-income-sources.tsx

- move Layout in each pages
- remove Layout from _app
Each page is expected to manage its own layout, although most pages (about 98%) will likely use the Layout component. However, there are exceptions, such as error and landing pages. Currently, the conditional rendering of the Layout component in the _app is causing issues with error pages that use the ErrorLayout component. Additionally, if a page needs to pass props to the Layout component, such as breadcrumb items, this would not be feasible if the component is placed in _app.

move Layout in each pages

---

frontend/src/middleware.ts

[AB#223](https://dev.azure.com/JourneyLab/e5439067-4cca-4d9d-9c04-19430d3be3db/_workitems/edit/223) (reprise) -- false positive "hidden files found" in OWASP ZAP due to `/*` page forwarding to `/en/*`
Some of the requests were not being handled correctly in `middleware.ts`.

Fix broken middleware processing

---

frontend/.env.example
frontend/next.config.js
frontend/src/pages/_app.tsx
frontend/src/pages/_document.tsx
frontend/src/utils/content-security-policy.ts

This pull request refactors the Content Security Policy (CSP) implementation for improved security. Here's what's changed:
- CSP has been moved to `_document.tsx` to enable the use of an `nonce`
- `'unsafe-inline'` has been removed to eliminate a potential security vulnerability
- All directives have been defaulted to 'none' for stricter control over content sources
- Unnecessary directives have been removed to further reduce potential attack surface
These changes provide a stronger defense against cross-site scripting (XSS) attacks and other security threats. Please review and merge at your earliest convenience.

[frontend] CSP: remove need for unsafe-inline

---

frontend/public/locales/en/learn/from-work-to-retirement.json

The incorrect from work to retirement page section EN title caused confusion if the link for index learning page was incorrect. The link is correct but the section title was not. Corrected the section title.
- Changed the section title to "From work to retirement"
npm i
npm run dev
got to http://localhost:3000/en/learn
click on the "From work to retirement" panel

correct the from-work-to-retirement page section title

---

frontend/src/components/ApplicationNameBar.tsx
frontend/src/components/Header.tsx
frontend/src/components/Layout.tsx
frontend/src/pages/learn/index.tsx
frontend/src/pages/quiz/tasks/[[...filters]].tsx

The checklist button should navigate users to the checklist page if they've submitted a quiz.  If they haven't and they click on the button, they should be navigated to the learn page.  
While on the checklist page, if a user clicks the restart quiz button, they will be redirected to the learn page and all memory of the completed quiz will be removed from storage.
- add logic to persist encoded quiz filters to local storage
- upon clicking the checklist button, check local storage to see if there are persisted quiz filters
- if yes, user is directed to the checklist page
- if no, user is directed to learn page
- reset quiz button on checklist page clears local storage and directs user to learn page

add logic for handling quiz in local storage

---

frontend/public/locales/fr/learn/retirement-income-sources.json

Fix French QPP link on /learn/retirement-sources-of-income page

change locale of french QPP link

---

frontend/src/pages/checklist/[filters].tsx

Based on some discussion, the filters shouldn't be visually styled to look like radio buttons.  The designers have settled on a check mark with outline instead of the radio checked look.  
See here in the mockups:
- swap out radio button icon with check icon
- add conditional styling
- cleanup old code

[frontend] change filter styles

---

frontend/src/components/quiz/QuizDialog.tsx

- fix: Closing quiz - Answers retained as long as user stays on learning page after closing quiz but will not produce a checklist if submitted. FormikWizard have a way to reset the form start but not the active step. I rendered the `QuizDialogWizard` conditionally to have a fresh state when the dialog is opening.

[frontend] fix AB#387

---

frontend/src/components/AccessibilityTable.tsx
frontend/src/components/LearnPageLayout.tsx

Add responsive container around a11y tables to ensure they're scrollable at smaller viewport widths.

[frontend] add responsive overflow to tables

---

frontend/src/lib/hooks/useQuizData.ts
frontend/src/lib/hooks/useRemoveQuizData.ts
frontend/src/lib/hooks/useSetQuizData.ts

- save quiz data in sessionStorage (instead of localeStorage)

[frontend] save quiz data in sessionStorage

---

frontend/src/pages/learn/case-studies/bonnie.tsx

Fixing a typo in the ID for a heading in the TOC on Bonnie's case study.

[frontend] change id to match heading in TOC

---

frontend/public/locales/fr/quiz.json
frontend/src/components/quiz/QuizDialog.tsx
frontend/src/pages/quiz.tsx

Add translations for the quiz. Modify styles and small layout changes
- primarily translations 
- the quiz next/prev buttons were also changed in accordance with the mockup.  Notice the order of the 'next' button and how it switches in mobile.

[frontend] add quiz translation

---

frontend/src/components/AccessibilityTable.tsx
frontend/src/pages/learn/case-studies/keith.tsx

Modify styles such that the "choices" text is left aligned on smaller screen instead of centred per the mockups.  Also remove the whitespace-nowrap on the accessibility table headers since it's still causing overflow on viewports around the 1000px width.

[frontend] change styles

---

frontend/__tests__/components/Footer.test.tsx
frontend/public/locales/en/common.json
frontend/public/locales/fr/common.json
frontend/src/components/Footer.tsx
frontend/src/components/Layout.tsx

- rename `Explore public pensions` to `Explore retirement`

[frontend] rename Explore public pensions to Explore retirement

---

frontend/src/pages/learn/rules-of-thumb-for-public-pensions.tsx

Remove duplicate ID on `<h3>`.  It isn't needed.

[frontend] remove duplicate id

---

frontend/public/locales/en/learn/case-studies/keith.json
frontend/public/locales/fr/learn/case-studies/keith.json
frontend/src/pages/learn/case-studies/keith.tsx

Fix case study for Keith.  Upon doing a manual a11y scan with Axe, there were some issues with the links in the OAS section.  I've changed the structure/locales to resolve.

[frontend] cleanup keith oas section

---

frontend/src/components/ApplicationNameBar.tsx
frontend/src/components/BreadcrumbStructuredData.tsx

- add Breadcrumb structured data
Set the following variable in `.env.local`:
```yaml
NEXT_PUBLIC_APP_BASE_URI=http://localhost:3000
```
https://developers.google.com/search/docs/appearance/structured-data/breadcrumb

[Frontend] add Breadcrumb structured data

---

frontend/src/theme.ts
frontend/tailwind.config.js

Not sure if this is the approach we should take, so here's a quick PR to adjust viewport breakpoints to align more with canada.ca.
I'm using [this as a reference](https://wet-boew.github.io/wet-boew-styleguide/design/grids-en.html)
From slack:

[frontend] attempt to get breakpoints closer to canada.ca

---

frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/src/pages/home.tsx

The tabs on the home page were flagged during an accessibility audit because they don't technically conform to the reflow WCAG success criterion even though they have a horizontal scroll.  The advice of the IT Accessibility Office was to either make the tabs stackable, or have a feature that can toggle tabs using a "more button".
- modify code to only display accessible tab picker on extra small (<600px) viewports
I couldn't figure out a way to do this cleanly with MUI.  The premise in this PR is that the "more button" will expand/collapse the tabs that you select from.  Unfortunately I couldn't figure out how to have 1 tab separate and the others grouped in a collapseable sections without MUI throwing an error about the other tab missing from the available …

[frontend] a11y tabs on home page

---

frontend/src/pages/checklist/[filters].tsx

- as per the mockups the `Restart quiz` button should be in the left section on larger screens and at the bottom of the page on smaller screens. Note: I kept the outlined button style.
Larger screens
Smaller screens

[frontend] checklist restart quiz buttons

---

frontend/src/components/NestedAccordion.tsx
frontend/src/theme.ts

- Accessibility caught an issue with our focus styling across the site having insufficient contrast, since a 3:1 contrast ratio made the text difficult to read on most elements I've swapped everything out with a focus outline instead.
- Disabled Ripple Effects, all button elements now have box-shadow outline on focus
- Tab through site elements to see new outlines, this should resolve the a11y issue since the new color has a 9:1 ratio
- 
- Re-created PR to fix merge issue

AB#454 A11y Contrast Issue

---

gitops/environments/production/deployments.patch.yaml

Bumping prod version to `20230601-0032-f7bfd6ba` to test the production GitOps TeamCity job.

[gitops] Bump prod to 20230601-0032-f7bfd6ba

---

frontend/.env.example
frontend/src/pages/_document.tsx

Add CSP `unsafe-inline` script directives when Adobe Analytics is enabled.

[frontend] Add unsafe-inline CSP for AA

---

frontend/src/components/NestedAccordion.tsx
frontend/src/pages/checklist/[filters].tsx

Set the checklist accordions expanded state persistant on change using url query string. That way if a user navigate away by with any links in task and go back then the user should see the same page state as before.
- checklist accordions persistent state using query string

[frontend] checklist accordions persistent state

---

frontend/src/pages/_document.tsx

Adding missing `canada.sc.omtrdc.net` domain to CSP headers.

[frontend] Add missing AA domain

---

frontend/src/components/NestedAccordion.tsx

This PR is intended to fix the issue of having a 1px layout shift in the y-axis when the accordion summary is opened on the checklist page.

[frontend] change styles on checklist accordion to prevent layout shift

---

frontend/public/locales/en/home.json
frontend/public/locales/en/learn.json
frontend/public/locales/en/learn/main-sources-of-retirement-income.json
frontend/public/locales/fr/home.json
frontend/public/locales/fr/learn.json
frontend/src/pages/home.tsx
frontend/src/pages/learn/index.tsx

- Made the following QC Changes
Landing Page
- In dev - tab card is 40% width, should be 33%  or 4/12 columns
- in dev - Top learning links style doesn't match spec for link headers or descriptions
- In dev - "Find a SC office" button border outline is the wrong colour, button text is too small
- Plan tab - Link for OAS benefits estimator should be https://www.canada.ca/en/services/benefits/pub licpensions/cpp/old-age-security/payments.html
Learning Page
- Banner quiz text needs to be updated
- In dev - overline and content cards in general are not to spec
- in dev - update retirement story blurb
- in dev - update Keith's blurb
Main Sources of Retirement
- Key takeaway is capitalized
- Trying to batch these changes as much as possible

QC Landing and Learning Pages

---

frontend/src/components/AccessibilityGraphContainer.tsx
frontend/src/components/AccessibilityTable.tsx

Modification to accessibility table to make columns even width and to add padding to the bottom of the table caption.
Here's how it looks:

[frontend] change a11y table to meet specs

---

frontend/public/locales/en/learn/main-sources-of-retirement-income.json
frontend/public/locales/fr/learn/main-sources-of-retirement-income.json
frontend/src/pages/learn/main-sources-of-retirement-income.tsx

QC Changes for Main Sources of Retirement Income Include
- in dev -  A three-pillar system table fonts  doesn't match spec
- typo corrected - flagged in Figma (Do you qualify for the OAS pension)
- Spacing for all Helpful resources incorrect
- Header style for What is the CPP Post- Retirement Benefit (PRB)? Changed to H3
- 2 instances where CPP retirement pensions changed to CPP retirement pension
- RRSP Important tip needs to be updated
- Learn more blurb for "Deciding when to start  your public pensions" updated in Figma - typo.
- Typo - extra you in last paragraph in Personal retirement savings. Updated in Figma with  comment
- Expanded CRA name - commented in Figma

QC For Main Sources of Retirement Income

---

frontend/src/pages/checklist/[filters].tsx

This PR is intended to align the checklist controls on the side of the page with the mock up specs.
Here's how it looks after the changes:
Desktop:
Mobile:

[frontend] change checklist controls styles

---

frontend/public/locales/en/checklist.json
frontend/public/locales/fr/checklist.json
frontend/src/components/NestedAccordion.tsx
frontend/src/components/TaskCard.tsx
frontend/src/pages/checklist/[filters].tsx

The premise of this PR is to introduce a screen reader only label to each chip (A.K.A. the task tags) in the checklist.  This will make for a more accessible experience to screen reader users.  
- added 'sr-only' span to the Chip component

[frontend] task tag sr-only

---

frontend/src/components/NestedAccordion.tsx

The intent of this PR is to align the nested accordion component's styles to match the Figma mockup.  Additional padding/margin added where it's needed as well as borders.
Here's how it looks now:

[frontend] modify nested accordion styles

---

frontend/src/pages/checklist/[filters].tsx

Checklist buttons should be clickable not from the expandable arrow icon, but rather from the entire width of the label and icon.  
Image of focus state: 
Mobile:

[frontend] change checklist control labels to also be clickable

---

frontend/src/components/AccessibilityGraphContainer.tsx

This is a purely cosmetic change that addresses one of the bugs flagged.  The spacing in the accessibility container needed to be adjusted. This PR resolves that issue and aligns the application with the mockups.

[frontend] adjust a11y table and container spacing

---

frontend/public/locales/en/learn/case-studies/bonnie.json
frontend/public/locales/en/learn/case-studies/fred.json
frontend/src/components/AccessibilityGraphContainer.tsx
frontend/src/components/AccessibilityTable.tsx

Small changes to align the accessibility headers with the mockups and to address some typos in the headers for Bonnie and Fred's case study.

[frontend] update accessibility header styles and fix typos in case study headers

---

frontend/public/locales/en/home.json
frontend/public/locales/fr/home.json
frontend/src/pages/home.tsx

An Pham asked to remove the "Contact us" section from the home page.
- remove home contact us section

[frontend] remove home contact us section

---

frontend/src/components/TableOfContents.tsx

Updated styles on the side navigation to match the mockup.
Here's how it looks:
NOTE: I didn't change styles on mobile since it isn't needed.

[frontend] modify table of contents side nav

---

frontend/src/components/Footer.tsx

This PR intends to address the padding between the privacy and terms and conditions links in the footer.
**After:**
**Before:**

[frontend] change padding on privacy links in footer

---

frontend/src/components/TaskGroupAccordion.tsx
frontend/src/pages/home.tsx

Add custom data attributes to components that the AA team shared with us.
- add custom data-gc attribute to learn tabs on home page
- add custom data-gc attribute to checklist timeline accordions
I need to add in the ones for the quiz. This will be addressed in a separate PR.

[frontend] add adobe analytic data attributes

---

frontend/src/components/HeroBanner.tsx
frontend/src/pages/_document.tsx
frontend/src/pages/checklist/[filters].tsx
frontend/src/pages/home.tsx
frontend/src/pages/learn/index.tsx

-  image placeholder blur for banners and cards images.
It's using the local images import. Next.js will automatically determine the width and height of your image based on the imported file. These values are used to prevent Cumulative Layout Shift while your image is loading.
https://nextjs.org/docs/pages/api-reference/components/image#local-images
Blurred images

[frontend] image placeholder blur

---

frontend/src/components/TableOfContentsDialog.tsx

Add a focus visible indicator to the table of contents button on learn pages.  This indicator should be visible when the component receives keyboard focus:
How it looks:

[frontend] add focus visible indicator to TOC button

---

frontend/src/components/TaskAccordion.tsx
frontend/src/components/TaskGroupAccordion.tsx
frontend/src/pages/checklist/[filters].tsx

- Checklist page bug where if the Important Terms and Filter Tasks section were opened first they would cause the accordions to open as well has been fixed. Can be re-produced by opening one of these sections while accordions are closed
- Added transition effect on the Accordion opening (not sure if this was removed intentionally?)
- Removed focus outline on accordion for consistency with other Collapse elements
- Fresh PR

Checklist Accordion Bug and Formatting

---

frontend/src/pages/quiz.tsx

This PR addresses the changes to the quiz disclaimer list.  Padding left has been adjusted to match the Figma mock up.

[frontend] adjust padding on quiz disclaimer list

---

frontend/src/components/quiz/QuizDialog.tsx

Adjust minimum modal close confirmation height:

[frontend] adjust close modal confirmation height

---

frontend/Dockerfile
frontend/next.config.js
frontend/src/instrumentation.node.ts
frontend/src/instrumentation.ts

- open-telemetry setup using instrumentation hook
Doing it that way fixes @sebastien-comeau issues when stopping next dev process. He has terminal piling over and over and could only stop them manually with task manager. Implemented Next.js OpenTelemetry guide fixed the issue.
https://nextjs.org/docs/app/building-your-application/optimizing/open-telemetry

[frontend] open-telemetry setup

---

frontend/src/components/quiz/QuizDialog.tsx

This PR aims to address the usability issue of having the modal focus remain on either the Previous button or Next button upon button press.  The intended behaviour is that on a navigation click, the focus should be placed on the closest interactive component to the top of the modal.  In this case, that would be the close button.

[frontend] make modal focus on close button on navigation

---

frontend/src/components/quiz/QuizDialog.tsx

Adjust padding to remove outline clipping when interactive components receive focus inside of quiz:

[frontend] fix outline clipping in quiz

---

frontend/src/components/AccessibilityGraphContainer.tsx
frontend/src/components/AccessibilityTable.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx

The intent of this PR is to address comments from the design team and the testing team for the Main Source of Retirement Income page accessibility table.  
Here is the discourse from Slack:
The end result is that by adding an optional boolean flag to the accessibility table props, we can surgically control the width of the table columns.  This is absolutely ground breaking code right here, enjoy...

[frontend] add autoWidthColumn prop to a11y table

---

frontend/src/pages/home.tsx
frontend/src/pages/learn/index.tsx

- French banner text is too long to be 6xl in md viewports see images for changes
- Button text aligned center
Before:
After:

Update French Banner Text Size

---

frontend/src/components/quiz/questions/QuestionWhere.tsx

This PR aims to address the issue of certain quiz buttons have text wrap when the viewport is small:
The first button shows the after and the second button shows the before:

[frontend] contain underline quiz buttons

---

frontend/src/components/TableOfContents.tsx
frontend/src/components/TableOfContentsDialog.tsx
frontend/src/pages/learn/main-sources-of-retirement-income.tsx

- fix heading elements are not in a sequentially-descending order (accessiblity issue)

[frontend] fix heading elements are not in a sequentially-descending order

---

frontend/src/pages/home.tsx

Remove `data-gc-analytics-tabopen` attribute on home page per AA team request.

[frontend] remove data-gc-analytics-tabopen

---

frontend/public/locales/en/checklist.json
frontend/public/locales/fr/checklist.json
frontend/src/pages/checklist/[filters].tsx

This PR is based on the latest requests from the Design Team in relation to adding a feature to open all tasks on demand, and subsequently close all tasks on demand.  
This is a screenshot of the requirements from the Design Team as of 21 June 2023:
- add open/close button beside the print button to toggle the task/group state to either be open or closed
- update the url based on expanded groups, tasks, and filters
- hide the print button when the page is in print mode

[frontend] add open/close all tasks logic

---

frontend/__tests__/lib/mappers/quiz-form-state-mapper.test.ts
frontend/src/lib/mappers/quiz-form-state-mapper.ts

- fix(fontend): quiz-form-state-mapper missing skip answer
- writtend quiz-form-state-mapper unit tests
There was a bug with `getAnswers` that affected the `marital-status-skip` when the array of anwers value was empty.

fix(fontend): quiz-form-state-mapper missing skip answer

---

infrastructure/terragrunt/nonprod/oauth-proxy-aad-application/terragrunt.hcl

Since prod is no longer protected by OAuth proxy, I'm removing the OAuth callbacks from the terraform files.
**Note: this changeset has already been applied via `terragrunt apply`**

[infrastructure] Remove prod oauth callbacks

---

frontend/Dockerfile

CVE-2023-32002 hsa been flagged by Dynatrace as Critical.
- fix: CVE-2023-32002
Node version 18.17.1 have fixes for CVE-2023-32002
https://github.com/nodejs/node/releases/tag/v18.17.1

fix: CVE-2023-32002

---

frontend/package-lock.json

Bump sharp to 0.32.6 to address [Vulnerability in libwebp dependency, please upgrade sharp to 0.32.6 (CVE-2023-4863) ](https://github.com/lovell/sharp/issues/3798)

[frontend] bump sharp

---

frontend/Dockerfile

- Bump docker base image to 20.9.0-bookworm-slim

Bump docker base image to 20.9.0-bookworm-slim

---

frontend/src/next-seo.config.ts

- fix(frontend): handle urlcat error
Url pathname with `/actuator/jolokia/search/*:test=test` was throwing an error when calling urlcat when the page responded with error 500 and should return a 404.
{
"level": 50,
"time": "2023-12-20T00:13:28.904Z",
"pid": 1364,
"hostname": "...",
"name": "next-seo-config",
"err": {
"type": "Error",
"message": "Missing value for path parameter test.",
"stack": "Error: Missing value for path parameter test.\n    at validatePathParam (file:///C:/data/projects/DTS-STN/senior-journey/frontend/node_modules/urlcat/dist/index.mjs:77:11)\n    at file:///C:/data/projects/DTS-STN/senior-journey/frontend/node_modules/urlcat/dist/index.mjs:68:5\n    at String.replace (<anonymous>)\n    at path …

fix(frontend): handle urlcat error

---

frontend/Dockerfile
frontend/package-lock.json
frontend/package.json

NodeJS was accidentally bumped past the LTS version in a dependabot PR. This reverts that and updates node to the latest container image and typescript types.

Fix nodejs versions

---

gitops/environments/dev/ingresses.yaml
gitops/environments/production/ingresses.yaml
gitops/environments/staging/ingresses.yaml
gitops/environments/test/ingresses.yaml

these changes let the checklist url redirect without a hard /, and don't forward the querystring with the redirect for the checklist.
- Changes to checklist redirects
Changes are live on dev.
They can go live when ready. No need to plan a release.

Touching up Redirects to New Site
